name: Publish Binaries

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        job_name:
          - linux
          - osx
          - win
        include:
          - job_name: linux
            os: ubuntu-latest
          - job_name: osx
            os: macos-11
          - job_name: win
            os: windows-latest

    name: '${{ matrix.job_name }}'
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.16.1
      - run: npm i

      # Build Linux
      - name: Build on Linux
        run: 'npm run build:linux'
        if: success() && matrix.job_name == 'linux'

      - name: Upload Linux Packages
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/dist/Rambox-*-linux-amd64.deb
            ${{ github.workspace }}/dist/Rambox-*-linux-i386.deb
            ${{ github.workspace }}/dist/Rambox-*-linux-amd64.snap
            ${{ github.workspace }}/dist/Rambox-*-linux-x86_64.AppImage
            ${{ github.workspace }}/dist/Rambox-*-linux-i386.AppImage
            ${{ github.workspace }}/dist/Rambox-*-linux-x86_64.rpm
            ${{ github.workspace }}/dist/Rambox-*-linux-i686.rpm
            ${{ github.workspace }}/dist/Rambox-*-linux-x64.tar.gz
            ${{ github.workspace }}/dist/Rambox-*-linux-ia32.tar.gz
            ${{ github.workspace }}/dist/Rambox-*-linux-x64.zip
            ${{ github.workspace }}/dist/Rambox-*-linux-ia32.zip
            ${{ github.workspace }}/dist/latest-linux.yml
            ${{ github.workspace }}/dist/latest-linux-ia32.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.job_name == 'linux'

      # Build OSX
      - name: Build on OSX
        run: 'npm run build:osx'
        if: success() && matrix.job_name == 'osx'

      - name: Upload OSX Packages
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/dist/Rambox-*-mac-universal.zip
            ${{ github.workspace }}/dist/Rambox-*-mac-universal.dmg
            ${{ github.workspace }}/dist/Rambox-*-mac-universal.dmg.blockmap
            ${{ github.workspace }}/dist/latest-mac.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.job_name == 'osx'

      # Build Windows
      - name: Build on Windows
        run: 'npm run build:win'
        if: success() && matrix.job_name == 'win'

      - name: Upload Windows Packages
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/dist/Rambox-*-win.exe
            ${{ github.workspace }}/dist/Rambox-*-win-x64.zip
            ${{ github.workspace }}/dist/Rambox-*-win-ia32.zip
            ${{ github.workspace }}/dist/Rambox-*-win.exe.blockmap
            ${{ github.workspace }}/dist/latest.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.job_name == 'win'
